### ISSUE TITLE
wrong response

### ISSUE THREAD

**Issue by allen1986** [asyrjasalo/RESTinstance#100]
I got wrong response when use RESTInstance GET method, the response contains some weird chracter seems like color code. below is test case and response:

```
*** Settings ***
Library           REST      http://localhost:8085

*** Test Cases ***
GET token from server
    GET     /token
    Output     $.code
    Should Be Equal As Strings     $.code      40001
```
```
================================================================
Test
================================================================
GET token from server                                                 .
?[34m40001?[39;49;00m
GET token from server                                                 | FAIL |
$.code != 40001
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
================================================================
```

**Comment by asimell** [comment]
Hi @allen1986 

`Should Be Equal As Strings` is a [builtin](https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Should%20Be%20Equal%20As%20Strings) keyword, not a keyword in this library. `$.code` doesn't evaluate into your response since the builtin keyword doesn't know anything about your response object.

You can store the response into a variable and then evaluate if that is equal to your expected value, e.g
```
${code}=    Output    $.code
Should Be Equal As Strings    ${code}    40001
```

or you can use the `String` or `Integer` keywords directly to check whether the code is expected, e.g.
```
String    $.code    40001
```

**Comment by asimell** [comment]
Closing issue as there is no new information.
