### ISSUE TITLE
Can not use Delete with a body

### ISSUE THREAD

**Issue by CapDam** [asyrjasalo/RESTinstance#4]
I looked at the code and it seems impossible to use Delete with a body:

> def delete(self, endpoint, timeout=None, allow_redirects=None, validate=True):

**Comment by asyrjasalo** [comment]
Thanks for submitting an issue. This currently works as it is by design, basing on the REST best practices. Although sending body in DELETE is not explicitly forbidden, it is not recommended.

According to [RFC 7231, "Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content"](https://tools.ietf.org/html/rfc7231#section-4.3.5):
>    A payload within a DELETE request message has no defined semantics;
>    sending a payload body on a DELETE request might cause some existing
>    implementations to reject the request.

Please create a new issue describing the real-world use-case, that possibly needs this to be compromised. For discussion on the topic, see e.g. Stack Overflow discussion on [Is an entity body allowed for an HTTP DELETE request?](https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request).
